FaceRecognition.Web/ViewModels/Detection/DetectionViewModel.cs
using FaceDetection.Web.Utilities;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;

namespace FaceDetection.Web.ViewModels.Detection
{
    public class DetectionViewModel
    {
        public string ImageBase64 { get; set; }

        public DetectionViewModel() { }

        public static DetectionViewModel Build(Bitmap image)
        {
            var detectionViewModel = new DetectionViewModel
            {
                ImageBase64 = ImageUtilities.ImageToBase64(image)
            };

            return detectionViewModel;
        }

        public Bitmap GetImage()
        {
            return ImageUtilities.Base64ToImage(ImageBase64);
        }
    }
}

FaceRecognition.Web/ViewModels/Recognition/TrainViewModel.cs
using FaceDetection.Library.Models;
using FaceDetection.Web.ViewModels.Detection;
using System;
using System.Collections.Generic;

namespace FaceDetection.Web.ViewModels.Recognition
{
    public class TrainViewModel : DetectionViewModel
    {
        public SimplePerson Person { get; set; }

        public TrainViewModel() : base() { }
    }
}

FaceRecognition.Web/ViewModels/Recognition/TrainingViewModel.cs
using FaceDetection.Library.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FaceDetection.Web.ViewModels
{
    public class TrainingViewModel
    {
        public FileModel File { get; set; }
    }
}

FaceRecognition.Web/Controllers/Api/DetectionController.cs
using FaceDetection.Library;
using FaceDetection.Library.Models;
using FaceDetection.Library.ViewModels;
using FaceDetection.Web.Utilities;
using FaceDetection.Web.ViewModels;
using FaceDetection.Web.ViewModels.Detection;
using FaceDetection.Web.ViewModels.Recognition;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;

namespace FaceDetection.Web.Controllers
{
    public class DetectionController : ApiController
    {
        private readonly FaceRecognitionLibrary _faceDetectionLibrary;

        public DetectionController(): base()
        {
            //string faceHaarCascadePath = HttpContext.Current.Server.MapPath("~/Files/haarcascade_frontalface_alt.xml");
            //string eyeHaarCascadePath = HttpContext.Current.Server.MapPath("~/Files/haarcascade_eye.xml");
            string connectionString = ConfigurationManager.ConnectionStrings["FaceDetectionContext"].ConnectionString;

            _faceDetectionLibrary = new FaceRecognitionLibrary(connectionString);
        }

        [HttpPost]
        public DetectionViewModel Detect(DetectionViewModel detectionViewModel)
        {
            var faceBitmap = detectionViewModel.GetImage();
            var faces = _faceDetectionLibrary.FindFaces(faceBitmap);

            faceBitmap = _faceDetectionLibrary.DrawFacesBoundsOnBitmap(faceBitmap, faces);
            detectionViewModel = DetectionViewModel.Build(faceBitmap);

            return detectionViewModel;
        }

        [HttpPost]
        public IHttpActionResult Train(TrainViewModel trainViewModel)
        {
            var faceBitmap = trainViewModel.GetImage();
            var faceRecognitionTrainingStatus = _faceDetectionLibrary.TrainFaceRecognition(faceBitmap, trainViewModel.Person);

            switch (faceRecognitionTrainingStatus)
            {
                case FaceDetection.Library.Models.FaceRecognitionTrainingStatus.TrainingSuccessful:
                    return Ok();
                case FaceDetection.Library.Models.FaceRecognitionTrainingStatus.FoundMoreThenOneFace:
                    return BadRequest("Found more then one face.");
                case FaceDetection.Library.Models.FaceRecognitionTrainingStatus.NoFacesFound:
                    return BadRequest("No faces found.");
                case FaceDetection.Library.Models.FaceRecognitionTrainingStatus.TrainingFailure:
                    return BadRequest("Training failure.");
                default:
                    return BadRequest();
            }
        }
        [HttpPost]
        public IHttpActionResult Training(TrainingViewModel zipWithFaces)
        {
            var trainingResult = _faceDetectionLibrary.TrainFaceRecognition(zipWithFaces.File);

            return Ok(trainingResult);
        }

        [HttpPost]
        public IHttpActionResult Recognition(DetectionViewModel detectionViewModel)
        {
            var faceBitmap = detectionViewModel.GetImage();
            var personsOnImage = _faceDetectionLibrary.FaceRecognition(faceBitmap);

            if (personsOnImage == null)
            {
                return BadRequest("No faces found.");
            }
            else if (personsOnImage.Count == 0)
            {
                return BadRequest("Face recognition could not found any persons on image.");
            }
            else if (personsOnImage.Count == 1)
            {
                var personOnImage = personsOnImage.First();

                if (personOnImage.RecognitionStatus == FaceRecognitionStatus.FaceRecognitionFailure 
                    || personOnImage.RecognitionStatus == FaceRecognitionStatus.FaceRecognitionError)
                {
                    if (personOnImage.PersonOnFace == null)
                    {
                        return BadRequest("Face recognition failed with eigen distance " + personOnImage.EigenDistance + ".");
                    }
                    else
                    {
                        return BadRequest("Face recognition failed with eigen distance " + personOnImage.EigenDistance + 
                            ". Presumed person on image is: "+personOnImage.PersonOnFace.FirstName+ " "+ personOnImage.PersonOnFace.LastName);
                    }
                }
            }
            
            return Ok(personsOnImage);
        }
    }
}

FaceRecognition.Web/Controllers/Mvc/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FaceDetection.Web.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        public ActionResult Index()
        {
            return View();
        }
	}
}

FaceRecognition.Web/Controllers/Mvc/TrainingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FaceDetection.Web.Controllers.Mvc
{
    public class TrainingController : Controller
    {
        // GET: Training
        public ActionResult Index()
        {
            return View();
        }
    }
}

FaceRecognition.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content" ng-controller="CameraController" ng-file-drop>
    <div class="row">
        <div class="content-section col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Posnemi sliko z kamero</h3>
                </div>
                <div class="panel-body">
                    <webcam on-stream="onStream(stream,video)" on-access-denied="onError(err)" on-streaming="onSuccess(video)" height="500" width="500">
                        <div class="alert alert-error" ng-show="webcamError">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong>Warning!</strong> Better check yourself, you're not looking too good.
                        </div>
                    </webcam>
                </div>
                <div class="panel-footer clearfix">
                    <div class="pull-left">
                        <button class="btn btn-danger" ng-click="onStopVideoClick()" type="button">Premor</button>
                    </div>
                    <div class="pull-right">
                        <button class="btn btn-success" ng-click="onTakeSnapshotClick()" type="button">Posnemi sliko</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-section col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Naloži sliko z diska</h3>
                </div>
                <div class="panel-body">
                    <div class="dropzone well well-sm" ng-file-over="hover">
                        <div class="dropzone-control-wrapper">
                            <div class="dropzone-control-section center-text">
                                Povlecite in spustite datoteko sem
                            </div>
                            <div class="dropzone-control-section center-text">
                                ali
                            </div>
                            <div class="dropzone-control-section">
                                <span class="btn btn-default btn-file center-element">
                                    <span class="btn-file-text">Izberite datoteke
                                    </span>
                                    <input class="file-upload-control" name="fileBase" ng-file-select type="file">
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="content-section col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Predogled naložene slike</h3>
                </div>
                <div class="panel-body">
                    <canvas class="face-detection-snapshot"></canvas>
                </div>
                <div class="panel-footer clearfix">
                    <div class="pull-left">
                        <button class="btn btn-primary" ng-click="onDetectFacesClick()" type="button">Najdi obraze na sliki</button>
                    </div>
                    <div class="pull-right">
                        <button class="btn btn-success" ng-click="onFaceRecognitionClick()" type="button">Razpoznaj obraze na sliki</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-section col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Obdelana slika</h3>
                </div>
                <div class="panel-body">
                    <div class="face-detection-result">
                        <div class="face-detection-error ng-hide" ng-show="detectionError">
                            <div class="alert alert-danger alert-dismissable">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <strong>Oh snap!</strong>
                                {{ detectionError.message }}
                            </div>
                        </div>
                        <div class="face-detection-success ng-hide" ng-show="detectionSuccess">
                            <div class="alert alert-success alert-dismissable">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <strong>Success!</strong>
                                {{ detectionSuccess.message }}
                            </div>
                        </div>
                        <div class="face-detection-found ng-hide" ng-show="recognitionSuccess">
                            <ul class="media-list">
                                <li class="media" ng-repeat="personWithFace in personsWithFace">
                                    <div class="media-body">
                                        <h4 class="media-heading">{{ personWithFace.personOnFace.firstName }} {{ personWithFace.personOnFace.lastName }}</h4>
                                        <div>
                                            X: {{ personWithFace.faceForPerson.x }}, Y: {{ personWithFace.faceForPerson.y }}
                                        </div>
                                        <div>
                                            Širina: {{ personWithFace.faceForPerson.width }}, Višina: {{ personWithFace.faceForPerson.height }}
                                        </div>
                                        <div>
                                            Eigenova dolžina: {{ personWithFace.eigenDistance}}
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <canvas class="face-detection-processed"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>

FaceRecognition.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="faceDetection">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="@Url.Content("~/Public/assets/css/vendor/bootstrap/bootstrap.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Public/assets/css/main.css")" rel="stylesheet" />
    <script data-main="@Url.Content("~/Public/assets/js/main.js")" src="~/Public/assets/js/vendor/requirejs/require.js"></script>		
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Detekcija obrazov", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Treniranje", "Index", "Training", null, new { @class = "navbar-brand" })
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

FaceRecognition.Web/Views/Training/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content" ng-controller="TrainingController" ng-file-drop>
    <div class="row">
        <div class="content-section col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Posnemi sliko z kamero</h3>
                </div>
                <div class="panel-body">
                    <webcam on-stream="onStream(stream,video)" on-access-denied="onError(err)" on-streaming="onSuccess(video)" height="500" width="500">
                        <div class="alert alert-error" ng-show="webcamError">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong>Warning!</strong> WebCam not working
                        </div>
                    </webcam>
                </div>
                <div class="panel-footer clearfix">
                    <div class="pull-left">
                        <button class="btn btn-danger" ng-click="onStopVideoClick()" type="button">Premor</button>
                    </div>
                    <div class="pull-right">
                        <button class="btn btn-success" ng-click="onTakeSnapshotClick()" type="button">Posnemi sliko</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-section col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Naloži sliko z diska</h3>
                </div>
                <div class="panel-body">
                    <div class="dropzone well well-sm" ng-file-over="hover">
                        <div class="dropzone-control-wrapper">
                            <div class="dropzone-control-section center-text">
                                Povlecite in spustite datoteko sem
                            </div>
                            <div class="dropzone-control-section center-text">
                                ali
                            </div>
                            <div class="dropzone-control-section">
                                <span class="btn btn-default btn-file center-element">
                                    <span class="btn-file-text">
                                        Izberite datoteke
                                    </span>
                                    <input class="file-upload-control" name="fileName" ng-file-select type="file">
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="content-section col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Posneta slika</h3>
                </div>
                <div class="panel-body">
                    <canvas class="face-detection-processed"></canvas>
                </div>
                <div class="panel-footer clearfix ng-hide" ng-show="showTrainingPanel">
                    <form role="form">
                        <div class="row clearfix">
                            <div class="form-group col-sm-6">
                                <input class="form-control" ng-model="person.firstName" placeholder="Vpišite ime" value="{{person.firstName}}" />
                            </div>
                            <div class="form-group col-sm-6">
                                <input class="form-control" ng-model="person.lastName" placeholder="Vpišite priimek" value="{{person.lastName}}" />
                            </div>
                            <div class="form-group col-sm-12 clearfix">
                                <div class="pull-right">
                                    <button type="button" class="btn btn-primary" ng-click="onEndTrainingClick()">Začni trening</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="content-section col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Obvestila</h3>
                </div>
                <div class="panel-body">
                    <div class="face-detection-error ng-hide" ng-show="trainingError">
                        <div class="alert alert-danger alert-dismissable">
                            <button type="button" class="close" aria-hidden="true">&times;</button>
                            <strong>Oh snap!</strong>
                            {{ trainingError.message }}
                        </div>
                    </div>
                    <div class="face-detection-success ng-hide" ng-show="trainingSuccess">
                        <div class="alert alert-success alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong>Success!</strong>
                            {{ trainingSuccess.message }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>